### ISSUE TITLE
Не работает код из примера

### ISSUE THREAD

**Issue by BusinessDuck** [nitreojs/tamtam#3]
Код из примера выдает ошибку
![image](https://user-images.githubusercontent.com/10143411/83942025-dd045c80-a7f8-11ea-88e9-22bc61ea1dad.png)

`TamTamError: attachments[0].payload.buttons[0].<list element>[0].payload: must not be null, attachments[0].payload.buttons[0].<list element>[1].payload: must not be null`

**Comment by nitreojs** [comment]
Последнее обновление кода было еще в конце октября 2019, а дальше улучшать модуль я не собираюсь - мне перестал быть интересен TamTam, я занимаюсь модулем **puregram**, так что советую просто перейти на другой действующий модуль.
